### ISSUE TITLE
Document how prepare the runtime to work on documentation

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#149]
To manage docs efficiently, users and developers must know how to build them. We need instructions on generating documentation with the docker image and locally downloaded project repository.

Section: Developer 101
Subsection: Work with the documentation

**Comment by denisvmedyantsev** [comment]
Savant contains Sphinx documentation in the docs folder. Due to some additional Sphinx requirements, we use a separate docker container to build the documentation. We prepared make commands to build the documentation locally easily.
1. `make build-docs`
2. `make run-docs`
3. open the root documentation page in browser `http://localhost:63342/savant/docs/build/html/index.html`

You need to run `make build-docs` once. After you have changed something in the docs/ (.rst files) or savant/ (.py files) folder, all you need to do is run `make run-docs` again and refresh the page in your browser (we mounted specified folders and there is no need to re-build docker).
