### ISSUE TITLE
Run benchmarks with queues and without them

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#352]
No queues, q=1, q=10
x86, Jetson NX

**Comment by bwsw** [comment]
exp_name: string, ticket, release

uridecodebin: 
- no_q, q=10, primary batch_size: 1, 4, 8

stream adapter:
- no_q, q=10, primary batch_size(`>= streams`) 1, 4, 8
- nstreams: 1, 2, 4, 8


1. Runtime for launching in a single command with JSON output.
2. To choose an analytical solution.

**Comment by denisvmedyantsev** [comment]
[logs folder](https://drive.google.com/drive/u/1/folders/1FfNgxC4JL40_TvurAgupYIu-HL-Ty6DQ)

**Comment by denisvmedyantsev** [comment]
[performance doc update](https://github.com/insight-platform/Savant/blob/352-perf-benchmark/docs/performance.md)

The increase in speed is due to the reconfiguration of the modules during metering. Now original module config is updated, output_frame encoding and draw_func is turned off (set to null).
