### ISSUE TITLE
`media_files_src_bin` uses same source-id for all videos in a folder

### ISSUE THREAD

**Issue by Y-T-G** [insight-platform/Savant#604]
It would be better if `media_files_src_bin` dynamically changed source_id for each video or image in a folder. It makes it easier to save them as different files using video file sink adapter which saves based on source_id.

**Comment by bwsw** [comment]
Hello, the problem is not related to the source adapter. It does not change source id because it allows processing chunked files as a continuous object.

The problem is related to the sink adapter mostly, but we believe sinks are purpose built. So because the sink receives the information about the source files in meta, it can handle it properly. Just do not forget enable EOS-sending.

Another trivial option is to use a shell script around the source:

```bash
ls | while read f
do
  run source source-id=$f
done
```

**Comment by Y-T-G** [comment]
@bwsw The video files adapter sink creates a .mov video file with the source-id as the name. So when processing another video from the same folder, it just overwrites the previous video with EOS. So how do I prevent that?

**Comment by bwsw** [comment]
@Y-T-G it may be a bug.

**Comment by tomskikh** [comment]
There's a bug: when `CHUNK_SIZE=0` the sink adapter creates only one file `video.mp4` and overwrite it after each EOS.

**Comment by bwsw** [comment]
@Y-T-G you can set `CHUNK_SIZE` to a large value and try again. We consider the report as a bug and fix.

**Comment by bwsw** [comment]
@tomskikh let us fix that please.
