### ISSUE TITLE
Substitution parameter not supported in Image File Sink and Video File Sink

### ISSUE THREAD

**Issue by Y-T-G** [insight-platform/Savant#609]
The documentation for Image File Sink and Video File Sink says:

>` DIR_LOCATION`: a location to write files to; can be a regular path or a path template; supported substitution parameters are `%source_id` and `%src_filename`;

But only JSON Metadata Sink supports this. In the code, I don't see any pattern replacement being done for Image File Sink and Video File Sink.

**Comment by tomskikh** [comment]
@Y-T-G @bwsw In video files sink we start every file with a keyframe since otherwise the file would be broken. When `EOS_ON_FILE_END=False` (this is a default value) on a video files source the first frame of the second file after the module can be not a keyframe. The only way how to support saving different source files to different locations is to append first frames (until keyframe is met) from the seconds files to the output of the first file. That should be noted in the documentation.

**Comment by tomskikh** [comment]
@Y-T-G Note that the first frame of a video file sould be a keyframe.
That mean that video files sink should start a new chunk only on a keyframe.

E.g.: A source adapter sent two files (`1.mp4`, `2.mp4`) to the module. The module encoded 5 first frames from `2.mp4` as non-keyframes; a frame #6 is a keyframe. In that case the video files sink adapter should write those 5 frames to the last chunk for `1.mp4`. Then the adapter should create a chunk for `2.mp4` and write frame #6 (keyframe) and the following frames to this chunk.

**Comment by bwsw** [comment]
Related to #772
