### ISSUE TITLE
Support metadata in the KVS source adapter

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#715]
The full metadata cycle requires transferring them with video data.

The first and the last UUIDs must be extracted to the KVS block and attached as attributes to a frame.

- "first-frame-uuid": uuid
- "last-frame-uuid": uuid

**Comment by bwsw** [comment]
User must be able to configure the adapter to:
1. place all serialized metadata in the compatible format under a key corresponding to a frame in the batch.
2. specify a user-defined Python function allowing to access frame meta and ingest custom fields based on the user's needs.

```
METADATA_INJECTOR_MODULE=my.module
METADATA_INJECTOR_FUNCTION=MyFunction
METADATA_INJECTOR_PARAMS=string
```

API (draft):

```python
class Injector(logger):
  def __init__(self, params):
    ...
  def inject(self, frame: VideoFrame) -> Dict[str, str]:
    ...
```

**Comment by tomskikh** [comment]
Cannot use `GST_EVENT_TAG` to parse UUIDs since `matroskademux` sends tags after frames from segment. This also happens when sending an event to `appsrc` before pushing fragment in `appsrc`. The only place to inject frame UUIDs into frame metadata is before `zeromq_sink`.

Also `matroskademux` could cause mamory leak since it doesn't clean `extended-comment` tags: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/1335
