### ISSUE TITLE
'There is no place on frame to put object image'

### ISSUE THREAD

**Issue by pranavsrihari123** [insight-platform/Savant#826]
I am consistently getting this error when preprocessing objects for an AttributeModel.

As far as I can understand, the preprocessing function in the ObjectsPreprocessing class attempts to fit all the resized object images within the dimensions of the original frame. My question is, why is this being done? Given that my original frame is 640x640 and my resized object image is 192x256, does this mean only 6 object images can be detected without throwing the above value error?

Is my understanding of this function correct? 

Any help would be greatly appreciated.

**Comment by bwsw** [comment]
@pranavsrihari123  Hi. Savant supports three preprocessing methods:
1. Nvinfer standard preprocessing configured for the nvinfer element. This is what you typically use by default, and it is used ALWAYS.
2. Preprocess object meta with custom Python function, which allows modifying padding, coordinates, crop, etc BEFORE (1).
3. Preprocess object image with custom Python function which allows custom image manipulation for ROI, like increase the contrast, rotate, etc. BEFORE (1).

When you use (3) you do not normally scale the ROI to network input, etc, because it is done by (1) you just correct the current ROI to prepare it for (1), e.g. when you use Oriented BB, you may rotate, when the ROI is dark, your correct colors. Thus, ROIs always fit the original image. We, indeed, make a copy of the original image and place ROIs on it (similar to the Knapsack packing algorithm) before passing them to Nvinfer (1). We do it that way as a temporary workaround solution.

E.g. 
- you do not need (2) & (3) if you just use YOLO for object detection with coaxial bounding boxes.
- you do need (3) if you detect LPs or faces and try to align them by keypoints.
- you do need (2) if you need to crop a certain part of the object for a later model, e.g., the model detected a person, but you need only their head.

**Comment by pranavsrihari123** [comment]
Is Nvinfer standard preprocessing configured to use symmetric padding or asymmetric padding? 

I am trying to use a pose estimation model (rtmpose), but it's hard to accurately convert the keypoints to the original ROI because I am unsure how nvinfer is scaling the image.

**Comment by bwsw** [comment]
@pranavsrihari123 you'd better check Nvidia documentation, but quickly looking I see they have symmetrical padding: https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_plugin_gst-nvinfer.html
