### ISSUE TITLE
Implement low-latency togglers for decoder

### ISSUE THREAD

**Issue by bwsw** [insight-platform/Savant#851]
A user must be able to specify:

```yaml
parameters:
  decoder_low_latency: True
```

to enable them.

- Jetson-specific switches (disable-dpb, enable-max-performance)
- dGPU-specific switches (low-latency-mode) 

Docs: https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_plugin_gst-nvvideo4linux2.html

Port to 0.4, 0.5

**Comment by bwsw** [comment]
Play till the badge to see the time skew (~3 sec).

![image](https://github.com/user-attachments/assets/5ee8b002-273f-4a27-af8c-d507273e36af)

Left: ffplay 
Right: ffmpeg adapter + display sink (~ +3 sec)

[Screencast from 09-03-2024 05:32:35 PM.webm](https://github.com/user-attachments/assets/b57ec6c3-f8ec-46a2-a7ce-7b80a5964017)

**Comment by tomskikh** [comment]
> Play till the badge to see the time skew (~3 sec).

Those 3 seconds because of `SYNC_INPUT=True` in Always-On-sink (default value).

**Tested on samples/telemetry**

Without low-latency decoding: 
![Screenshot from 2024-09-04 16-47-40](https://github.com/user-attachments/assets/77ae63fc-e669-43e0-b864-af1368892647)

With low-latency decoding:
![Screenshot from 2024-09-04 16-47-45](https://github.com/user-attachments/assets/09c1c640-b0e8-4ce4-adc9-b27300709544)

Time spent on decoding reduced from 33ms to 1.5ms.

**Tested with RTSP stream from local mediamtx server**

Without low-latency decoding: 
![Screenshot from 2024-09-04 16-51-07](https://github.com/user-attachments/assets/8ea6fe00-2f58-464f-923e-639f64c151dc)

With low-latency decoding:
![Screenshot from 2024-09-04 16-52-17](https://github.com/user-attachments/assets/8c06f58e-07ce-4a17-abef-4183c801b6e9)

Delay reduced from 120ms to 80ms.

**Comment by bwsw** [comment]
Cool!
